import idx from 'idx'
import { simpleUserSchema } from '../schema'
import type { EntityDataProps, ReferenceProps, SchemaConfig } from './Types'
import EntitySchema from './Entity'
import { attachmentSchema, simpleTagSchema } from '../../../src/schema'
import { nextTrackerId } from './Tracker'
